name: Rust Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
      - run: rustup component add clippy
      - uses: 10XGenomics/clippy-check@ed0387fa7a8848cc4a39b448220856192673e355
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          name: xtimer